### ISSUE TITLE
Delete payment endpoint 

### ISSUE THREAD

**Issue by agrcom** [Respekto/posesor-backend#16]
User Story
As user I would like to remove payment for subject, when removed payment was last document for subjectName, the subject should be also removed.

Assignments:
- add possibility to delete payment in posesor-payment 
- add posibility to delete subject in posesor-subject

AC:
- payment service is able to delete payment 
- after delete posesor-payment will sent request to posesor-subject and check if subjectName is used for other documents, if not it should be removed.

**Comment by siudeks** [comment]
Usuwam jako stare i nie aktualizowane
